name: "Link a solution"
description: "You built it. Now let's connect it to the problem it solves."
title: "Solution: <issue name>"
labels: ["solution", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## You did it.

        Somewhere, a researcher is about to get hours of their life back because of what you built. Let's make sure they can find it.

  - type: input
    id: issue
    attributes:
      label: Which Resolve issue does this solve?
      placeholder: "#6 env-rescue"
    validations:
      required: true

  - type: input
    id: repo
    attributes:
      label: Repo URL
      placeholder: "https://github.com/org/tool"
    validations:
      required: true

  - type: dropdown
    id: status
    attributes:
      label: Status
      options:
        - "In Progress -- it's usable but still evolving"
        - "Solved -- it works and it's ready for users"
    validations:
      required: true

  - type: textarea
    id: proof
    attributes:
      label: Show us it works
      description: "A link to docs, a demo, a screenshot, a GIF -- whatever best demonstrates that the friction is resolved."
      placeholder: |
        - README with quickstart: https://github.com/org/tool#quickstart
        - Demo GIF showing the full workflow
        - Example output from a real use case
    validations:
      required: true

  - type: input
    id: license
    attributes:
      label: License
      placeholder: "MIT, Apache-2.0, BSD-3-Clause"
    validations:
      required: true

  - type: textarea
    id: team
    attributes:
      label: Who built this?
      description: "List everyone who contributed. They'll all be credited in the Resolved section."
      placeholder: |
        @alice - core logic and domain expertise
        @bob - CLI, packaging, and CI
        @carol - documentation and testing
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Anything else?
      description: "Known limitations, supported platforms, future plans -- whatever helps users and maintainers."
      placeholder: "Currently supports CIF and SDF formats. PDB support planned for v0.2."
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---

        *Once this is reviewed, we'll update the registry and add your team to the Resolved section. Thanks for making research a little less frustrating.*
